/* 
 * Copyright 2011 ClinRisk Ltd.
 * 
 * This file is part of QCancer(Gastro-oesophageal) (http://qcancer.org/gastro-oesophageal, http://svn.clinrisk.co.uk/opensource/qcancer/gastro-oesophageal).
 * 
 * QCancer(Gastro-oesophageal) is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * QCancer(Gastro-oesophageal) is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with QCancer(Gastro-oesophageal).  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Additional terms
 * 
 * The following disclaimer must be displayed alongside any risk score generated by this code.
 *   The initial version of this file, to be found at http://svn.clinrisk.co.uk/opensource/qcancer/gastro-oesophageal, faithfully implements QCancer(Gastro-oesophageal).
 *   We have released this code under the GNU Lesser General Public License to enable others to implement the algorithm faithfully.
 *   However, the nature of the GNU Lesser General Public License is such that we cannot prevent, for example, someone altering the coefficients.
 *   We stress, therefore, that it is the responsibility of the end user to check that the source that they receive produces the same results as the original code posted at http://svn.clinrisk.co.uk/opensource/qcancer/gastro-oesophageal.
 *   Inaccurate implementations of risk scores can lead to wrong patients being given the wrong treatment.
 * 
 * This file has been auto-generated.
 * XML source: Q64_oesgastric_stcox_event_29_1.xml
 * STATA dta time stamp: 18 May 2011 12:50
 * This file was created on: Thu  3 Nov 2011 11:49:24 GMT
 */

#include <math.h>
#include <string.h>
#include <clinrisk/Q64_oesgastric_stcox_event_29_1.h>
#include <clinrisk/utils.h>

static double oesgastric_male_raw(
int age,int c_hb,int new_abdopain,int new_appetiteloss,int new_dysphagia,int new_gibleed,int new_weightloss,int smoke_cat,int surv
)
{
	double survivor[3] = {
		0,
		0.999867320060730,
		0.999817907810211
	};

	/* The conditional arrays */

	double Ismoke[5] = {
		0,
		0.3235278058725861200000000,
		0.6375974591579122200000000,
		0.7774212108976175100000000,
		0.6946519648812690100000000
	};

	/* Applying the fractional polynomial transforms */
	/* (which includes scaling)                      */

	double dage = age;
	dage=dage/10;
	double age_1 = pow(dage,-2);
	double age_2 = pow(dage,3);

	/* Centring the continuous variables */

	age_1 = age_1 - 0.041110929101706;
	age_2 = age_2 - 119.967628479003910;

	/* Start of Sum */
	double a=0;

	/* The conditional sums */

	a += Ismoke[smoke_cat];

	/* Sum from continuous values */

	a += age_1 * -95.2461515621876490000000000;
	a += age_2 * 0.0006801747814227366000000;

	/* Sum from boolean values */

	a += c_hb * 0.5831595971250255200000000;
	a += new_abdopain * 1.3298636277554265000000000;
	a += new_appetiteloss * 1.3529521374542517000000000;
	a += new_dysphagia * 4.9643544294615367000000000;
	a += new_gibleed * 2.0305965190571675000000000;
	a += new_weightloss * 1.7292332247479998000000000;

	/* Sum from interaction terms */

	a += age_1 * new_dysphagia * 11.3293521469324240000000000;
	a += age_2 * new_dysphagia * -0.0031872056744650782000000;

	/* Calculate the score itself */
	double score = 100.0 * (1 - pow(survivor[surv], exp(a)) );
	return score;
}

static int oesgastric_male_validation(
int age,int c_hb,int new_abdopain,int new_appetiteloss,int new_dysphagia,int new_gibleed,int new_weightloss,int smoke_cat,int surv,char *errorBuf,int errorBufSize
)
{
	int ok=1;
	*errorBuf=0;
	if (!i_in_range(age,30,84)) {
		ok=0;
		strlcat(errorBuf,"error: age must be in range (30,84)\n",errorBufSize);
	}
	if (!is_boolean(c_hb)) {
		ok=0;
		strlcat(errorBuf,"error: c_hb must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(new_abdopain)) {
		ok=0;
		strlcat(errorBuf,"error: new_abdopain must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(new_appetiteloss)) {
		ok=0;
		strlcat(errorBuf,"error: new_appetiteloss must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(new_dysphagia)) {
		ok=0;
		strlcat(errorBuf,"error: new_dysphagia must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(new_gibleed)) {
		ok=0;
		strlcat(errorBuf,"error: new_gibleed must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(new_weightloss)) {
		ok=0;
		strlcat(errorBuf,"error: new_weightloss must be in range (0,1)\n",errorBufSize);
	}
	if (!i_in_range(smoke_cat,0,4)) {
		ok=0;
		strlcat(errorBuf,"error: smoke_cat must be in range (0,4)\n",errorBufSize);
	}
	if (!i_in_range(surv,1,2)) {
		ok=0;
		strlcat(errorBuf,"error: surv must be in range (1,2)\n",errorBufSize);
	}
	return ok;
}

double oesgastric_male(
int age,int c_hb,int new_abdopain,int new_appetiteloss,int new_dysphagia,int new_gibleed,int new_weightloss,int smoke_cat,int surv,int *error,char *errorBuf,int errorBufSize
)
{
	*error = 0;	int ok = oesgastric_male_validation(age,c_hb,new_abdopain,new_appetiteloss,new_dysphagia,new_gibleed,new_weightloss,smoke_cat,surv,errorBuf,errorBufSize);
	if(!ok) { 
		*error = 1;
		return 0.0;
	}
	return oesgastric_male_raw(age,c_hb,new_abdopain,new_appetiteloss,new_dysphagia,new_gibleed,new_weightloss,smoke_cat,surv);
}
