/* 
 * Copyright 2011 ClinRisk Ltd.
 * 
 * This file is part of QDScore (http://qdscore.org, http://svn.clinrisk.co.uk/opensource/qdscore).
 * 
 * QDScore is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * QDScore is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with QDScore.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Additional terms
 * 
 * The following disclaimer must be displayed alongside any risk score generated by this code.
 *   The initial version of this file, to be found at http://svn.clinrisk.co.uk/opensource/qdscore, faithfully implements QDScore.
 *   We have released this code under the GNU Lesser General Public License to enable others to implement the algorithm faithfully.
 *   However, the nature of the GNU Lesser General Public License is such that we cannot prevent, for example, someone altering the coefficients.
 *   We stress, therefore, that it is the responsibility of the end user to check that the source that they receive produces the same results as the original code posted at http://svn.clinrisk.co.uk/opensource/qdscore.
 *   Inaccurate implementations of risk scores can lead to wrong patients being given the wrong treatment.
 * 
 * This file has been auto-generated.
 * XML source: Q67_qdscore_2011_5_0.xml
 * STATA dta time stamp: 9 May 2011 11:01
 * This file was created on: Wed 22 Jun 2011 10:48:53 BST
 */

#include <math.h>
#include <string.h>
#include <clinrisk/Q67_qdscore_2011_5_0.h>
#include <clinrisk/utils.h>

static double type2_female_raw(
int age,int b_corticosteroids,int b_cvd,int b_treatedhyp,double bmi,int ethrisk,int fh_diab,int smoke_cat,int surv,double town
)
{
	double survivor[16] = {
		0,
		0.998757064342499,
		0.997445642948151,
		0.996133863925934,
		0.994613707065582,
		0.992973208427429,
		0.991180300712585,
		0.989336967468262,
		0.987273931503296,
		0.984970986843109,
		0.982576668262482,
		0.980043888092041,
		0.977539658546448,
		0.975032866001129,
		0.972225964069366,
		0.969546496868134
	};

	/* The conditional arrays */

	double Iethrisk[10] = {
		0,
		0,
		1.2139020162839465000000000,
		1.3951431007871689000000000,
		2.0769065284533896000000000,
		1.1985281424438017000000000,
		0.4435163515045756900000000,
		0.3334214312431622600000000,
		1.3593218385581369000000000,
		0.7630012562805385000000000
	};
	double Ismoke[5] = {
		0,
		0.0838917077444029660000000,
		0.1521184571187761700000000,
		0.2779859392335956600000000,
		0.4194792563852659500000000
	};

	/* Applying the fractional polynomial transforms */
	/* (which includes scaling)                      */

	double dage = age;
	dage=dage/10;
	double age_1 = pow(dage,.5);
	double age_2 = pow(dage,3);
	double dbmi = bmi;
	dbmi=dbmi/10;
	double bmi_1 = dbmi;
	double bmi_2 = pow(dbmi,3);

	/* Centring the continuous variables */

	age_1 = age_1 - 2.136317968368530;
	age_2 = age_2 - 95.059478759765625;
	bmi_1 = bmi_1 - 2.541280746459961;
	bmi_2 = bmi_2 - 16.411865234375000;
	town = town - -0.145694017410278;

	/* Start of Sum */
	double a=0;

	/* The conditional sums */

	a += Iethrisk[ethrisk];
	a += Ismoke[smoke_cat];

	/* Sum from continuous values */

	a += age_1 * 4.3850736594887181000000000;
	a += age_2 * -0.0049725629200767941000000;
	a += bmi_1 * 3.2621272806944703000000000;
	a += bmi_2 * -0.0593431115390273410000000;
	a += town * 0.0476418698532814970000000;

	/* Sum from boolean values */

	a += b_corticosteroids * 0.2962932643694408700000000;
	a += b_cvd * 0.3885763437441697200000000;
	a += b_treatedhyp * 0.5338016808735898100000000;
	a += fh_diab * 0.7232263224304240600000000;

	/* Sum from interaction terms */

	a += age_1 * bmi_1 * 2.2996230877151524000000000;
	a += age_1 * bmi_2 * -0.1008429993378986300000000;
	a += age_1 * fh_diab * -0.7560619223432010200000000;
	a += age_2 * bmi_1 * -0.0080739440992934099000000;
	a += age_2 * bmi_2 * 0.0002769038765685592200000;
	a += age_2 * fh_diab * 0.0015682968672418253000000;

	/* Calculate the score itself */
	double score = 100.0 * (1 - pow(survivor[surv], exp(a)) );
	return score;
}

static int type2_female_validation(
int age,int b_corticosteroids,int b_cvd,int b_treatedhyp,double bmi,int ethrisk,int fh_diab,int smoke_cat,int surv,double town,char *errorBuf,int errorBufSize
)
{
	int ok=1;
	*errorBuf=0;
	if (!i_in_range(age,25,84)) {
		ok=0;
		strlcat(errorBuf,"error: age must be in range (25,84)\n",errorBufSize);
	}
	if (!is_boolean(b_corticosteroids)) {
		ok=0;
		strlcat(errorBuf,"error: b_corticosteroids must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_cvd)) {
		ok=0;
		strlcat(errorBuf,"error: b_cvd must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_treatedhyp)) {
		ok=0;
		strlcat(errorBuf,"error: b_treatedhyp must be in range (0,1)\n",errorBufSize);
	}
	if (!d_in_range(bmi,20,40)) {
		ok=0;
		strlcat(errorBuf,"error: bmi must be in range (20,40)\n",errorBufSize);
	}
	if (!i_in_range(ethrisk,1,9)) {
		ok=0;
		strlcat(errorBuf,"error: ethrisk must be in range (1,9)\n",errorBufSize);
	}
	if (!is_boolean(fh_diab)) {
		ok=0;
		strlcat(errorBuf,"error: fh_diab must be in range (0,1)\n",errorBufSize);
	}
	if (!i_in_range(smoke_cat,0,4)) {
		ok=0;
		strlcat(errorBuf,"error: smoke_cat must be in range (0,4)\n",errorBufSize);
	}
	if (!i_in_range(surv,1,15)) {
		ok=0;
		strlcat(errorBuf,"error: surv must be in range (1,15)\n",errorBufSize);
	}
	if (!d_in_range(town,-7,11)) {
		ok=0;
		strlcat(errorBuf,"error: town must be in range (-7,11)\n",errorBufSize);
	}
	return ok;
}

double type2_female(
int age,int b_corticosteroids,int b_cvd,int b_treatedhyp,double bmi,int ethrisk,int fh_diab,int smoke_cat,int surv,double town,int *error,char *errorBuf,int errorBufSize
)
{
	*error = 0;	int ok = type2_female_validation(age,b_corticosteroids,b_cvd,b_treatedhyp,bmi,ethrisk,fh_diab,smoke_cat,surv,town,errorBuf,errorBufSize);
	if(!ok) { 
		*error = 1;
		return 0.0;
	}
	return type2_female_raw(age,b_corticosteroids,b_cvd,b_treatedhyp,bmi,ethrisk,fh_diab,smoke_cat,surv,town);
}
