/* 
 * Copyright 2011 ClinRisk Ltd.
 * 
 * This file is part of QDScore (http://qdscore.org, http://svn.clinrisk.co.uk/opensource/qdscore).
 * 
 * QDScore is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * QDScore is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with QDScore.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Additional terms
 * 
 * The following disclaimer must be displayed alongside any risk score generated by this code.
 *   The initial version of this file, to be found at http://svn.clinrisk.co.uk/opensource/qdscore, faithfully implements QDScore.
 *   We have released this code under the GNU Lesser General Public License to enable others to implement the algorithm faithfully.
 *   However, the nature of the GNU Lesser General Public License is such that we cannot prevent, for example, someone altering the coefficients.
 *   We stress, therefore, that it is the responsibility of the end user to check that the source that they receive produces the same results as the original code posted at http://svn.clinrisk.co.uk/opensource/qdscore.
 *   Inaccurate implementations of risk scores can lead to wrong patients being given the wrong treatment.
 * 
 * This file has been auto-generated.
 * XML source: Q67_qdscore_2011_5_1.xml
 * STATA dta time stamp: 9 May 2011 11:01
 * This file was created on: Wed 22 Jun 2011 10:49:03 BST
 */

#include <math.h>
#include <string.h>
#include <clinrisk/Q67_qdscore_2011_5_1.h>
#include <clinrisk/utils.h>

static double type2_male_raw(
int age,int b_corticosteroids,int b_cvd,int b_treatedhyp,double bmi,int ethrisk,int fh_diab,int smoke_cat,int surv,double town
)
{
	double survivor[16] = {
		0,
		0.998294472694397,
		0.996437609195709,
		0.994502544403076,
		0.992287158966064,
		0.989889740943909,
		0.987343549728394,
		0.984665155410767,
		0.981661736965179,
		0.978376150131226,
		0.974755048751831,
		0.971110701560974,
		0.967482805252075,
		0.963613748550415,
		0.959616661071777,
		0.955506145954132
	};

	/* The conditional arrays */

	double Iethrisk[10] = {
		0,
		0,
		1.3105228602404502000000000,
		1.4501855668346837000000000,
		1.8939034483133890000000000,
		1.2170053256815645000000000,
		0.6805394576531532700000000,
		0.9125107090609191300000000,
		1.0505453905234938000000000,
		0.8235716338191840800000000
	};
	double Ismoke[5] = {
		0,
		0.1346713288453373900000000,
		0.1910475866658711800000000,
		0.3096621973367150700000000,
		0.4257219784473999000000000
	};

	/* Applying the fractional polynomial transforms */
	/* (which includes scaling)                      */

	double dage = age;
	dage=dage/10;
	double age_1 = log(dage);
	double age_2 = pow(dage,3);
	double dbmi = bmi;
	dbmi=dbmi/10;
	double bmi_1 = pow(dbmi,2);
	double bmi_2 = pow(dbmi,3);

	/* Centring the continuous variables */

	age_1 = age_1 - 1.497711062431335;
	age_2 = age_2 - 89.401130676269531;
	bmi_1 = bmi_1 - 6.789675235748291;
	bmi_2 = bmi_2 - 17.691860198974609;
	town = town - -0.064807504415512;

	/* Start of Sum */
	double a=0;

	/* The conditional sums */

	a += Iethrisk[ethrisk];
	a += Ismoke[smoke_cat];

	/* Sum from continuous values */

	a += age_1 * 4.5236024108368573000000000;
	a += age_2 * -0.0041630702096505838000000;
	a += bmi_1 * 1.1360916527041702000000000;
	a += bmi_2 * -0.1831779919050053900000000;
	a += town * 0.0300848931173275830000000;

	/* Sum from boolean values */

	a += b_corticosteroids * 0.2356834799017269400000000;
	a += b_cvd * 0.4020222357367155800000000;
	a += b_treatedhyp * 0.5176529543002307300000000;
	a += fh_diab * 0.8493767313150059100000000;

	/* Sum from interaction terms */

	a += age_1 * bmi_1 * 0.6897577585757245200000000;
	a += age_1 * bmi_2 * -0.1787859644798800400000000;
	a += age_1 * fh_diab * -1.0314506414078772000000000;
	a += age_2 * bmi_1 * -0.0019953060553397524000000;
	a += age_2 * bmi_2 * 0.0004331755365358763300000;
	a += age_2 * fh_diab * 0.0015888181435241716000000;

	/* Calculate the score itself */
	double score = 100.0 * (1 - pow(survivor[surv], exp(a)) );
	return score;
}

static int type2_male_validation(
int age,int b_corticosteroids,int b_cvd,int b_treatedhyp,double bmi,int ethrisk,int fh_diab,int smoke_cat,int surv,double town,char *errorBuf,int errorBufSize
)
{
	int ok=1;
	*errorBuf=0;
	if (!i_in_range(age,25,84)) {
		ok=0;
		strlcat(errorBuf,"error: age must be in range (25,84)\n",errorBufSize);
	}
	if (!is_boolean(b_corticosteroids)) {
		ok=0;
		strlcat(errorBuf,"error: b_corticosteroids must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_cvd)) {
		ok=0;
		strlcat(errorBuf,"error: b_cvd must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_treatedhyp)) {
		ok=0;
		strlcat(errorBuf,"error: b_treatedhyp must be in range (0,1)\n",errorBufSize);
	}
	if (!d_in_range(bmi,20,40)) {
		ok=0;
		strlcat(errorBuf,"error: bmi must be in range (20,40)\n",errorBufSize);
	}
	if (!i_in_range(ethrisk,1,9)) {
		ok=0;
		strlcat(errorBuf,"error: ethrisk must be in range (1,9)\n",errorBufSize);
	}
	if (!is_boolean(fh_diab)) {
		ok=0;
		strlcat(errorBuf,"error: fh_diab must be in range (0,1)\n",errorBufSize);
	}
	if (!i_in_range(smoke_cat,0,4)) {
		ok=0;
		strlcat(errorBuf,"error: smoke_cat must be in range (0,4)\n",errorBufSize);
	}
	if (!i_in_range(surv,1,15)) {
		ok=0;
		strlcat(errorBuf,"error: surv must be in range (1,15)\n",errorBufSize);
	}
	if (!d_in_range(town,-7,11)) {
		ok=0;
		strlcat(errorBuf,"error: town must be in range (-7,11)\n",errorBufSize);
	}
	return ok;
}

double type2_male(
int age,int b_corticosteroids,int b_cvd,int b_treatedhyp,double bmi,int ethrisk,int fh_diab,int smoke_cat,int surv,double town,int *error,char *errorBuf,int errorBufSize
)
{
	*error = 0;	int ok = type2_male_validation(age,b_corticosteroids,b_cvd,b_treatedhyp,bmi,ethrisk,fh_diab,smoke_cat,surv,town,errorBuf,errorBufSize);
	if(!ok) { 
		*error = 1;
		return 0.0;
	}
	return type2_male_raw(age,b_corticosteroids,b_cvd,b_treatedhyp,bmi,ethrisk,fh_diab,smoke_cat,surv,town);
}
